[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "https://bathily-convoyage.netlify.app/*"
  to = "https://bathily-convoyage.fr/:splat"
  status = 301
  force = true
