/**
 * Generate supabase-config.js and firebase-config.js from environment variables.
 * Run before vite build: node scripts/generate-config.js
 *
 * Required env vars:
 *   SUPABASE_URL, SUPABASE_ANON_KEY
 * Optional env vars:
 *   FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID,
 *   FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID
 */

const fs = require('fs');
const path = require('path');

const publicDir = path.resolve(__dirname, '..', 'public');
if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });

// --- Supabase ---
const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('⚠️  SUPABASE_URL or SUPABASE_ANON_KEY not set — supabase-config.js will use placeholder values.');
  console.warn('   Set them in your Netlify dashboard or local .env file.');
}

const supabaseContent = `// Auto-generated by scripts/generate-config.js — DO NOT EDIT MANUALLY
window.SUPABASE_URL = "${supabaseUrl || 'https://YOUR_PROJECT.supabase.co'}";
window.SUPABASE_ANON_KEY = "${supabaseAnonKey || 'YOUR_SUPABASE_ANON_KEY'}";
`;

fs.writeFileSync(path.join(publicDir, 'supabase-config.js'), supabaseContent);
console.log('✅ public/supabase-config.js generated');

// --- Firebase (optional) ---
const fbApiKey = process.env.FIREBASE_API_KEY || process.env.VITE_FIREBASE_API_KEY;
const fbAuthDomain = process.env.FIREBASE_AUTH_DOMAIN || process.env.VITE_FIREBASE_AUTH_DOMAIN;
const fbProjectId = process.env.FIREBASE_PROJECT_ID || process.env.VITE_FIREBASE_PROJECT_ID;
const fbStorageBucket = process.env.FIREBASE_STORAGE_BUCKET || process.env.VITE_FIREBASE_STORAGE_BUCKET;
const fbMessagingSenderId = process.env.FIREBASE_MESSAGING_SENDER_ID || process.env.VITE_FIREBASE_MESSAGING_SENDER_ID;
const fbAppId = process.env.FIREBASE_APP_ID || process.env.VITE_FIREBASE_APP_ID;

if (fbApiKey) {
  const firebaseContent = `// Auto-generated by scripts/generate-config.js — DO NOT EDIT MANUALLY
const firebaseConfig = {
  apiKey: "${fbApiKey}",
  authDomain: "${fbAuthDomain || ''}",
  projectId: "${fbProjectId || ''}",
  storageBucket: "${fbStorageBucket || ''}",
  messagingSenderId: "${fbMessagingSenderId || ''}",
  appId: "${fbAppId || ''}"
};
`;

  fs.writeFileSync(path.join(publicDir, 'firebase-config.js'), firebaseContent);
  console.log('✅ public/firebase-config.js generated');
} else {
  console.log('ℹ️  Firebase env vars not set — skipping firebase-config.js');
}
